In [2]:
import numpy as np

f = np.array([1, 2, 4, 7, 11, 16], dtype=float)
np.gradient(f)

array([1. , 1.5, 2.5, 3.5, 4.5, 5. ])

In [3]:
np.gradient(f, 2)

array([0.5 , 0.75, 1.25, 1.75, 2.25, 2.5 ])

In [4]:
x = np.arange(f.size)
np.gradient(f, x)

array([1. , 1.5, 2.5, 3.5, 4.5, 5. ])

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st

In [7]:
data = np.random.multivariate_normal((0, 0), [[0.8, 0.05], [0.05, 0.7]], 100)
print("data:", np.shape(data))
x = data[:, 0]
y = data[:, 1]
print("x:", np.shape(x))

xmin, xmax = -3, 3
ymin, ymax = -3, 3

xx, yy = np.mgrid[xmin:xmax:100j, ymin:ymax:100j]
print("xx:", np.shape(xx), np.shape(yy))
# print(xx)

positions = np.vstack([xx.ravel(), yy.ravel()])
print("positions:", np.shape(positions))
print(positions[0][0])
print(positions[1][0])

values = np.vstack([x, y])
print("values:", np.shape(values))

kernel = st.gaussian_kde(values)
f = np.reshape(kernel(positions).T, xx.shape)

data: (100, 2)
x: (100,)
xx: (100, 100) (100, 100)
positions: (2, 10000)
-3.0
-3.0
values: (2, 100)


In [14]:
logpdf = np.reshape(kernel.logpdf(positions),xx.shape)
gradient = np.gradient(logpdf)
print(np.shape(gradient))

(2, 100, 100)


In [18]:
print(np.max(gradient))
print(np.min(gradient))

1.1874913794004769
-1.0082838387238624
