In [2]:
import tensorflow as tf
import numpy as np

sess = tf.InteractiveSession()

a = tf.constant([1.0, 3.0])
b = tf.add(a, a)
print(b.eval(), type(b))

sess.close()

[2. 6.] <class 'tensorflow.python.framework.ops.Tensor'>


In [3]:
import sys

sess = tf.InteractiveSession()

x = tf.constant(3.0)
with tf.GradientTape() as g:
    g.watch(x)
    y = x * x
dy_dx = g.gradient(y, x) # Will compute to 6.0
tf.print(dy_dx, output_stream=sys.stderr)
print(dy_dx.eval(), type(dy_dx))

sess.close()

6.0 <class 'tensorflow.python.framework.ops.Tensor'>


In [4]:
from datetime import datetime
dim = 7000

startTime = datetime.now()
m1 = tf.truncated_normal([dim, dim], mean=0.0, stddev=0.02, dtype=tf.float32, seed=1)
print(datetime.now() - startTime)

startTime = datetime.now()
m1 = tf.truncated_normal([dim, dim], mean=0.0, stddev=0.02, dtype=tf.float32, seed=1)
sess = tf.Session()
sess.run(m1)
print(datetime.now() - startTime)

0:00:00.005004
0:00:00.538428


sess = tf.InteractiveSession()

matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
product = tf.matmul(matrix1, matrix2)

#print the product
print(product.eval())

#close the session to release resources
sess.close()

In [5]:
sess = tf.InteractiveSession()
x = [[1.,2.,1.],[1.,1.,1.]]    # a 2D matrix as input to softmax
y = tf.nn.softmax(x)           # this is the softmax function
                               # you can have anything you like here
u = y.eval()
print(u)
sess.close()

[[0.21194157 0.5761169  0.21194157]
 [0.33333334 0.33333334 0.33333334]]


In [6]:
def log_huber(x, m):
    if tf.abs(x) <= m:
        return x**2
    else:
        return m**2 * (1 - 2 * tf.log(m) + tf.log(x**2))

x = tf.placeholder(tf.float32)
m = tf.placeholder(tf.float32)

y = tf.py_function(func=log_huber, inp=[x, m], Tout=tf.float32)
dy_dx = tf.gradients(y, x)[0]

with tf.Session() as sess:
    # The session executes `log_huber` eagerly. Given the feed values below,
    # it will take the first branch, so `y` evaluates to 1.0 and
    # `dy_dx` evaluates to 2.0.
    y, dy_dx = sess.run([y, dy_dx], feed_dict={x: 1.0, m: 2.0})
    print(dy_dx)

2.0


In [1]:
import tensorflow as tf

tf.enable_eager_execution()

x = tf.ones((2, 2))
with tf.GradientTape() as t:
    t.watch(x)
    y = tf.reduce_sum(x)
    z = tf.multiply(y, y)

# Use the tape to compute the derivative of z with respect to the
# intermediate value y.
dz_dy = t.gradient(z, y)
assert dz_dy.numpy() == 8.0

In [1]:
import numpy as np
import tensorflow as tf

npc = np.array([[1.,2.],[3.,4.]])
tfc = tf.Variable(npc) # Use variable 

row = np.array([[.1,.2]])

with tf.Session() as sess:   
    tf.initialize_all_variables().run() # need to initialize all variables

    print('tfc:\n', tfc.eval())
    print('npc:\n', npc)
    for i in range(2):
        for j in range(2):
            npc[i,j] += row[0,j]
    tfc.assign(npc).eval() # assign_sub/assign_add is also available.
    print('modified tfc:\n', tfc.eval())
    print('modified npc:\n', npc)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
tfc:
 [[1. 2.]
 [3. 4.]]
npc:
 [[1. 2.]
 [3. 4.]]
modified tfc:
 [[1.1 2.2]
 [3.1 4.2]]
modified npc:
 [[1.1 2.2]
 [3.1 4.2]]


In [9]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
print(x1)
print(x2)
np.multiply(x1, x2)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[0. 1. 2.]


array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [11]:
# x2 = x2.reshape(1,3)
# print(x2)
a = np.matmul(x2, x1)
a + 1

array([16., 19., 22.])