In [2]:
import numpy as np
x = np.array([1,1,1],dtype=np.float32)
x.itemsize

4

In [4]:
np.sin(np.array([1,1,1],dtype=np.float32))

array([0.84147096, 0.84147096, 0.84147096], dtype=float32)

In [5]:
x = np.array([[1,2,3],[4,5,6]])
x.shape

(2, 3)

In [10]:
x = np.ones((3,3))
print(x)
y = x[:,[0,1,2,2]]
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
A = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x = np.matrix([[1],[0],[0]])
A*x

matrix([[1],
        [4],
        [7]])