In [1]:
import numpy as np

In [2]:
array = np.array([[1,2,3],[2,4,6]])
print(array)

[[1 2 3]
 [2 4 6]]


In [3]:
print('number of dim:', array.ndim) # dimmension
print('shape:', array.shape) # rows and columns
print('size:', array.size) # number of elements

number of dim: 2
shape: (2, 3)
size: 6


In [4]:
a = np.array([2,34,4]) # list 1d
print(a)

[ 2 34  4]


In [5]:
a = np.array([2,23,4],dtype=np.int)
print(a.dtype)

int32


In [7]:
a = np.array([2,23,4],dtype=np.int32)
print(a.dtype)

int32


In [8]:
a = np.array([2,23,4],dtype=np.float)
print(a.dtype)

float64


In [9]:
a = np.array([2,23,4],dtype=np.float32)
print(a.dtype)

float32


In [10]:
a = np.array([[2,23,4],[2,32,4]]) # 2d matrix, 2 rows and 3 columns
print(a)

[[ 2 23  4]
 [ 2 32  4]]


In [11]:
a = np.zeros((3,4)) # all 0. 3 rows and 4 columns
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
a = np.ones((3,4),dtype=np.int) # all 1. 3 rows and 4 columns
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [13]:
a = np.empty((3,4)) # data is empty. 3 rows and 4 columns
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
a = np.arange(10,20,2) # 10-19 and step size is 2
print(a)

[10 12 14 16 18]


In [15]:
a = np.arange(12).reshape(3,4) # reshape to 3 rows and 4 columns, 0-11
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [16]:
a = np.linspace(1,10,20) # [1, 10]. There are 20 data. float
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [18]:
a = np.linspace(1,10,20).reshape(5,4) # reshape
print(a)

[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]
