In [1]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)
print(a)
print(b)

[10 20 30 40]
[0 1 2 3]


In [4]:
c=a-b
print(c)

[10 19 28 37]


In [5]:
c=a+b
print(c)

[10 21 32 43]


In [6]:
c=a*b
print(c)

[  0  20  60 120]


In [14]:
c=b**2
print(c)

[[0 1]
 [4 9]]


In [8]:
c=10*np.sin(a)
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [9]:
print(b<3)

[ True  True  True False]


In [11]:
a=np.array([[1,1],[0,1]])
b=np.arange(4).reshape((2,2))
print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [15]:
c_dot=np.dot(a,b)
print(c_dot)
print(a*b)
c_dot2=a.dot(b)
print(c_dot2)

[[2 4]
 [2 3]]
[[0 1]
 [0 3]]
[[2 4]
 [2 3]]


In [16]:
# check sum(), min(), max()
a = np.random.random((2,4)) # from 0 to 1
print(a)

[[0.87759618 0.05905476 0.53507749 0.55023075]
 [0.5746939  0.22093567 0.82118112 0.71038088]]


In [17]:
print(np.sum(a))
print(np.min(a))
print(np.max(a))

4.349150760053933
0.05905476275882138
0.8775961831349015


In [18]:
print('a=',a)
print('sum=',np.sum(a,axis=0)) # choose 1st dimmension
print('sum=',np.sum(a,axis=1)) # choose 2nd dimmension
print('min=',np.min(a,axis=0))
print('max=',np.max(a,axis=1))

a= [[0.87759618 0.05905476 0.53507749 0.55023075]
 [0.5746939  0.22093567 0.82118112 0.71038088]]
sum= [1.45229008 0.27999044 1.35625861 1.26061163]
sum= [2.02195919 2.32719157]
min= [0.5746939  0.05905476 0.53507749 0.55023075]
max= [0.87759618 0.82118112]


In [20]:
A = np.arange(2,14).reshape((3,4))
print(A)
print(np.argmin(A)) # min index
print(np.argmax(A)) # max index

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11


In [21]:
print(np.mean(A)) # 7.5
print(np.average(A)) # 7.5

7.5
7.5


In [24]:
print(A.mean()) # 7.5

7.5


In [26]:
print(np.median(A)) # 7.5

7.5


In [25]:
print(np.cumsum(A)) # accumulation

[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [27]:
print(np.diff(A))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [28]:
print(np.nonzero(A))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [29]:
A = np.arange(14,2,-1).reshape(3,4)
print(A)
print(np.sort(A)) # sort by row

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [30]:
print(np.transpose(A))
print(A.T)

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [31]:
print(A)
print(np.clip(A,5,9))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]
