In [1]:
import numpy as np
A=np.arange(3,15)
print(A)
print(A[3])

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6


In [2]:
A=np.arange(3,15).reshape(3,4)
print(A)
print(A[2])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]


In [3]:
print(A[1][1])

8


In [4]:
print(A[1,1])

8


In [5]:
print(A[1,1:3])

[8 9]


In [6]:
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [7]:
for column in A.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [8]:
A=np.arange(3,15).reshape(3,4)
print(A.flatten())

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [10]:
for item in A.flat: # flat is an iterator
    print(item)

3
4
5
6
7
8
9
10
11
12
13
14
