In [2]:
import numpy as np

a=np.arange(4)
b=a
c=a
d=b

In [3]:
a[0]=11
print(a)

[11  1  2  3]


In [5]:
print(b is a)
print(c is a)
print(d is a)

True
True
True


In [6]:
d[1:3]=[22,33]
print(a)
print(b)
print(c)

[11 22 33  3]
[11 22 33  3]
[11 22 33  3]


In [7]:
b=a.copy() # deep copy
print(b)
a[3]=44
print(a)
print(b)

[11 22 33  3]
[11 22 33 44]
[11 22 33  3]
