[numpy一些方法总结](https://blog.csdn.net/u010156024/article/details/50419338)

In [10]:
import numpy as np

a = np.array([[0.1, .32, .2,  0.4, 0.8], [.23, .18, .56, .61, .12], [.9, .3, .6, .5, .3],  [.34, .75, .91, .19, .21]])
b = np.corrcoef(a)
print(np.shape(a), np.shape(b))
print(b)

vc = [1, 2, 39, 0, 8]
vb = [1, 2, 38, 0, 8]

print(np.mean(np.multiply((vc-np.mean(vc)),(vb - np.mean(vb)))) / (np.std(vb) * np.std(vc)))
print(np.corrcoef(vc, vb)) # cov matrix

(4, 5) (4, 4)
[[ 1.         -0.35153114 -0.74736506 -0.48917666]
 [-0.35153114  1.          0.23810227  0.15958285]
 [-0.74736506  0.23810227  1.         -0.03960706]
 [-0.48917666  0.15958285 -0.03960706  1.        ]]
0.999986231330961
[[1.         0.99998623]
 [0.99998623 1.        ]]


In [3]:
x1 = [1, 2, 3]
x2 = [4, 5, 6]
print(np.multiply(x1, x2))

[ 4 10 18]


In [4]:
b = [1, 3, 5, 6]
print(np.var(b)) # variance
print(np.power(np.std(b), 2)) # standard deviation
a1 = [[1, 2, 3, 4, 5,6], [3, 4, 5, 6, 7, 8]]
print(np.var(a1[0]))
print(np.var(a1,0)) # axis, column
print(np.var(a1, 1)) # axis, row

3.6875
3.6874999999999996
2.9166666666666665
[1. 1. 1. 1. 1. 1.]
[2.91666667 2.91666667]


In [5]:
b = [1, 3, 4, 5]
print(np.mean(b))
print(np.mean(a1))
print(np.mean(a1, 0)) # mean of column
print(np.mean(a1, 1)) # mean of row

3.25
4.5
[2. 3. 4. 5. 6. 7.]
[3.5 5.5]


In [6]:
x = [[0, 1, 2], [2, 1, 0]]
b = [1, 3, 5, 6]
print(np.sum(x))
print(np.sum(b))

6
15


In [8]:
b = [1, 3, 5, 6]
print(np.cov(b))
print(np.sum(np.multiply(b, b) - np.mean(b)* np.mean(b))/3)

4.916666666666666
4.916666666666667


In [9]:
x=[[0, 1, 2],[2, 1, 0]]
print(np.cov(x))
print(np.sum((np.multiply(x[0],x[1]))-np.mean(x[0]) * np.mean(x[1]))/2)

[[ 1. -1.]
 [-1.  1.]]
-1.0


In [11]:
print(np.complex(1,100)) # complex

(1+100j)


In [33]:
x1 = [1, 2, 3]
x2 = [4, 5, 6]
print(np.vdot(x1, x2)) # dot product 

32


In [34]:
x1 = [1, 2, 3]
x2 = [4, 5, 6]
xx = [x1, x2]
print(np.vdot(x1, x2)) # dot product
print(np.mat(x1)*np.mat(x2).T)
print(np.mat(xx))

32
[[32]]
[[1 2 3]
 [4 5 6]]


In [35]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.shape(a))
print(a.shape)

ones = np.ones((2,1))
print(ones)

(2, 3)
(2, 3)
[[1.]
 [1.]]


In [36]:
for i in range(3):
    print(i)

test = [1, 2, 3, 4]
print(test[:])
print(test[2:3])
for i in range(2, 5):
    print(i)

0
1
2
[1, 2, 3, 4]
[3]
2
3
4


In [37]:
import time
from datetime import datetime,date

dd = datetime.strptime('2014-04-03T10:53:49.875Z', "%Y-%m-%dT%H:%M:%S.%fZ")
print(time.mktime(dd.timetuple()))#1396493629.0

1396493629.0


In [38]:
print(np.linspace(0,3,6))

[0.  0.6 1.2 1.8 2.4 3. ]


In [39]:
arr = np.array([0.1, 0.6, 0.5, 0.7])
sortedIndex = np.argsort(arr)
print(sortedIndex)
print(arr)

[0 2 1 3]
[0.1 0.6 0.5 0.7]


In [40]:
dd = [1, 2, 3]
dilogdd = np.diag(dd)
print(dilogdd)

print(np.linalg.inv(dilogdd)) # inverse matrix
print(np.mat(dilogdd).I)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]
[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]]


In [41]:
x1 = [[1,2,3],[4,5,6],[7,8,9]]
d = np.dot(x1, x1) # matrix dot product
print(d)
print(np.mat(x1)*np.mat(x1))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [42]:
print(np.zeros((2, 3)))
print(np.eye(4))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [43]:
A = np.mat([[1,0,0,0,2],[0,0,3,0,0],[0,0,0,0,0],[0,4,0,0,0]])
U = A*A.T
lamda, hU = np.linalg.eig(U)
print(hU)
print(lamda)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 5.  9.  0. 16.]


In [47]:
A = np.mat([[1,0,0,0,2],[0,0,3,0,0],[0,0,0,0,0],[0,4,0,0,0]])
U,S,VT = np.linalg.svd(A)
print(U)
print(S)
print(VT)

[[ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 1.  0.  0.  0.]]
[4.         3.         2.23606798 0.        ]
[[-0.          1.          0.         -0.          0.        ]
 [-0.          0.          1.         -0.          0.        ]
 [ 0.4472136   0.          0.          0.          0.89442719]
 [ 0.          0.          0.          1.          0.        ]
 [-0.89442719  0.          0.          0.          0.4472136 ]]


In [49]:
x = [[1, 0, 0, 0, 2], [0, 0, 3, 0, 0]]
print(np.random.rand(3, 3))
print(np.nonzero(x)) # 1st line is row value, 2nd line is column value

[[0.28129716 0.81222135 0.57954806]
 [0.24199972 0.81729191 0.66791607]
 [0.77011977 0.3094823  0.70830644]]
(array([0, 0, 1], dtype=int64), array([0, 4, 2], dtype=int64))


In [50]:
for i in range(65, 70):
    print(str(chr(i)))

A
B
C
D
E


In [55]:
x1 = list(range(0, 9))
print(x1)
np.random.shuffle(x1)
print(x1)

[0, 1, 2, 3, 4, 5, 6, 7, 8]
[6, 7, 4, 5, 3, 0, 8, 2, 1]


In [64]:
np.random.seed(1)
print(np.random.uniform(-1,1,5)) # specify the range
print(np.random.random())
print(np.random.random(5))
print(np.random.rand(2, 3))
print(np.random.randint(5,10))
print(np.random.randint(5,10,size=(5,5)))

[-0.16595599  0.44064899 -0.99977125 -0.39533485 -0.70648822]
0.0923385947687978
[0.18626021 0.34556073 0.39676747 0.53881673 0.41919451]
[[0.6852195  0.20445225 0.87811744]
 [0.02738759 0.67046751 0.4173048 ]]
6
[[6 5 6 6 6]
 [6 5 9 6 5]
 [5 8 7 6 5]
 [8 6 6 8 9]
 [5 6 8 9 7]]


In [76]:
a = np.arange(0, 12)
a.shape = 3,4
print(a)
a.tofile("a.bin")
b = np.fromfile("a.bin", dtype=np.int32)
b.shape = 3,4
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [77]:
a = np.arange(0, 12)
a.shape = 3,4
print(a)
np.save('a.npy', a)
c = np.load('a.npy')
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [78]:
a = np.array([[1,2,3], [4,5,6]])
b = np.arange(0, 10, 0.1)
c = np.sin(b)
np.savez('result.npz', a, b, sin_array = c)
r = np.load('result.npz')
print(r['arr_0'])
print(r['arr_1'])
print(r['sin_array'])

[[1 2 3]
 [4 5 6]]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]
[ 0.          0.09983342  0.19866933  0.29552021  0.38941834  0.47942554
  0.56464247  0.64421769  0.71735609  0.78332691  0.84147098  0.89120736
  0.93203909  0.96355819  0.98544973  0.99749499  0.9995736   0.99166481
  0.97384763  0.94630009  0.90929743  0.86320937  0.8084964   0.74570521
  0.67546318  0.59847214  0.51550137  0.42737988  0.33498815  0.23924933
  0.14112001  0.04158066 -0.05837414 -0.15774569 -0.2555411  -0.35078323
 -0.44252044 -0.52983614 -0.61185789 -0.68776616 -0.7568025  -0.81827711
 -0.87157577 -0.91616594 -0.95160207 -0.97753012 -0.993691   -0

In [80]:
print(np.random.permutation(10)) # shuffle
print(np.random.permutation([1, 4, 9, 12, 15]))

[4 3 5 6 0 1 8 7 2 9]
[ 1  9  4 12 15]
